disabled_rules:
  - accessibility_trait_for_button
  - file_header
  - file_name  
  - force_cast
  - force_try
  - force_unwrapping
  - prohibited_interface_builder
  - blanket_disable_command
  # Prefer SwiftFormat
  - opening_brace
  - trailing_comma
  - sorted_imports
  - comma_inheritance
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - switch_case_on_newline
  - switch_case_alignment
opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle  
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count  
  - empty_xctest_method
  - expiring_todo
  # - explicit_enum_raw_value
  - explicit_init
  # - explicit_type_interface
  # - explicit_acl
  # - explicit_top_level_acl  
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - file_name_no_space
  # - file_types_order
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  # - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order  
  - nimble_operator
  - number_separator  
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - ns_number_init_as_function_reference
  # - no_extension_access_modifier
  # - no_grouping_extension
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  # - required_deinit
  - required_enum_case
  - return_value_from_void_function
  # - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - static_operator
  # - strict_fileprivate
  # - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  # - type_contents_order  
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  # - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  # - vertical_whitespace_between_cases
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition
analyzer_rules:
  - capture_variable
  # - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import
included:
  - ios/Classes
excluded:
  - ios/Classes/Messages.swift

line_length:
- 200   # warning
- 300   # error
large_tuple: 3
number_separator:
  minimum_length: 5

identifier_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on
    - db
  reporter: "xcode"