// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum messagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct SFSafariViewControllerOptions: Hashable, CustomStringConvertible {
  var preferredBarTintColor: Int64? = nil
  var preferredControlTintColor: Int64? = nil
  var barCollapsingEnabled: Bool? = nil
  var entersReaderIfAvailable: Bool? = nil
  var dismissButtonStyle: Int64? = nil
  var modalPresentationStyle: Int64? = nil
  var pageSheet: UISheetPresentationControllerConfiguration? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SFSafariViewControllerOptions? {
    let preferredBarTintColor: Int64? = nilOrValue(pigeonVar_list[0])
    let preferredControlTintColor: Int64? = nilOrValue(pigeonVar_list[1])
    let barCollapsingEnabled: Bool? = nilOrValue(pigeonVar_list[2])
    let entersReaderIfAvailable: Bool? = nilOrValue(pigeonVar_list[3])
    let dismissButtonStyle: Int64? = nilOrValue(pigeonVar_list[4])
    let modalPresentationStyle: Int64? = nilOrValue(pigeonVar_list[5])
    let pageSheet: UISheetPresentationControllerConfiguration? = nilOrValue(pigeonVar_list[6])

    return SFSafariViewControllerOptions(
      preferredBarTintColor: preferredBarTintColor,
      preferredControlTintColor: preferredControlTintColor,
      barCollapsingEnabled: barCollapsingEnabled,
      entersReaderIfAvailable: entersReaderIfAvailable,
      dismissButtonStyle: dismissButtonStyle,
      modalPresentationStyle: modalPresentationStyle,
      pageSheet: pageSheet
    )
  }
  func toList() -> [Any?] {
    return [
      preferredBarTintColor,
      preferredControlTintColor,
      barCollapsingEnabled,
      entersReaderIfAvailable,
      dismissButtonStyle,
      modalPresentationStyle,
      pageSheet,
    ]
  }
  static func == (lhs: SFSafariViewControllerOptions, rhs: SFSafariViewControllerOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.preferredBarTintColor, rhs.preferredBarTintColor) && messagesPigeonInternal.deepEquals(lhs.preferredControlTintColor, rhs.preferredControlTintColor) && messagesPigeonInternal.deepEquals(lhs.barCollapsingEnabled, rhs.barCollapsingEnabled) && messagesPigeonInternal.deepEquals(lhs.entersReaderIfAvailable, rhs.entersReaderIfAvailable) && messagesPigeonInternal.deepEquals(lhs.dismissButtonStyle, rhs.dismissButtonStyle) && messagesPigeonInternal.deepEquals(lhs.modalPresentationStyle, rhs.modalPresentationStyle) && messagesPigeonInternal.deepEquals(lhs.pageSheet, rhs.pageSheet)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SFSafariViewControllerOptions")
    messagesPigeonInternal.deepHash(value: preferredBarTintColor, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: preferredControlTintColor, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: barCollapsingEnabled, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: entersReaderIfAvailable, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: dismissButtonStyle, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: modalPresentationStyle, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: pageSheet, hasher: &hasher)
  }

  public var description: String {
    return "SFSafariViewControllerOptions(preferredBarTintColor: \(String(describing: preferredBarTintColor)), preferredControlTintColor: \(String(describing: preferredControlTintColor)), barCollapsingEnabled: \(String(describing: barCollapsingEnabled)), entersReaderIfAvailable: \(String(describing: entersReaderIfAvailable)), dismissButtonStyle: \(String(describing: dismissButtonStyle)), modalPresentationStyle: \(String(describing: modalPresentationStyle)), pageSheet: \(String(describing: pageSheet)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UISheetPresentationControllerConfiguration: Hashable, CustomStringConvertible {
  var detents: [String]
  var largestUndimmedDetentIdentifier: String? = nil
  var prefersScrollingExpandsWhenScrolledToEdge: Bool? = nil
  var prefersGrabberVisible: Bool? = nil
  var prefersEdgeAttachedInCompactHeight: Bool? = nil
  var preferredCornerRadius: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UISheetPresentationControllerConfiguration? {
    let detents = pigeonVar_list[0] as! [String]
    let largestUndimmedDetentIdentifier: String? = nilOrValue(pigeonVar_list[1])
    let prefersScrollingExpandsWhenScrolledToEdge: Bool? = nilOrValue(pigeonVar_list[2])
    let prefersGrabberVisible: Bool? = nilOrValue(pigeonVar_list[3])
    let prefersEdgeAttachedInCompactHeight: Bool? = nilOrValue(pigeonVar_list[4])
    let preferredCornerRadius: Double? = nilOrValue(pigeonVar_list[5])

    return UISheetPresentationControllerConfiguration(
      detents: detents,
      largestUndimmedDetentIdentifier: largestUndimmedDetentIdentifier,
      prefersScrollingExpandsWhenScrolledToEdge: prefersScrollingExpandsWhenScrolledToEdge,
      prefersGrabberVisible: prefersGrabberVisible,
      prefersEdgeAttachedInCompactHeight: prefersEdgeAttachedInCompactHeight,
      preferredCornerRadius: preferredCornerRadius
    )
  }
  func toList() -> [Any?] {
    return [
      detents,
      largestUndimmedDetentIdentifier,
      prefersScrollingExpandsWhenScrolledToEdge,
      prefersGrabberVisible,
      prefersEdgeAttachedInCompactHeight,
      preferredCornerRadius,
    ]
  }
  static func == (lhs: UISheetPresentationControllerConfiguration, rhs: UISheetPresentationControllerConfiguration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.detents, rhs.detents) && messagesPigeonInternal.deepEquals(lhs.largestUndimmedDetentIdentifier, rhs.largestUndimmedDetentIdentifier) && messagesPigeonInternal.deepEquals(lhs.prefersScrollingExpandsWhenScrolledToEdge, rhs.prefersScrollingExpandsWhenScrolledToEdge) && messagesPigeonInternal.deepEquals(lhs.prefersGrabberVisible, rhs.prefersGrabberVisible) && messagesPigeonInternal.deepEquals(lhs.prefersEdgeAttachedInCompactHeight, rhs.prefersEdgeAttachedInCompactHeight) && messagesPigeonInternal.deepEquals(lhs.preferredCornerRadius, rhs.preferredCornerRadius)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UISheetPresentationControllerConfiguration")
    messagesPigeonInternal.deepHash(value: detents, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: largestUndimmedDetentIdentifier, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: prefersScrollingExpandsWhenScrolledToEdge, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: prefersGrabberVisible, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: prefersEdgeAttachedInCompactHeight, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: preferredCornerRadius, hasher: &hasher)
  }

  public var description: String {
    return "UISheetPresentationControllerConfiguration(detents: \(String(describing: detents)), largestUndimmedDetentIdentifier: \(String(describing: largestUndimmedDetentIdentifier)), prefersScrollingExpandsWhenScrolledToEdge: \(String(describing: prefersScrollingExpandsWhenScrolledToEdge)), prefersGrabberVisible: \(String(describing: prefersGrabberVisible)), prefersEdgeAttachedInCompactHeight: \(String(describing: prefersEdgeAttachedInCompactHeight)), preferredCornerRadius: \(String(describing: preferredCornerRadius)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SFSafariViewControllerOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return UISheetPresentationControllerConfiguration.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SFSafariViewControllerOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? UISheetPresentationControllerConfiguration {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CustomTabsApi {
  func launchURL(_ urlString: String, prefersDeepLink: Bool, options: SFSafariViewControllerOptions?, completion: @escaping (Result<Void, Error>) -> Void)
  func closeAllIfPossible(completion: @escaping (Result<Void, Error>) -> Void)
  func mayLaunchURLs(_ urlStrings: [String]) throws -> String?
  func invalidateSession(_ sessionId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CustomTabsApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CustomTabsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CustomTabsApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let launchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.launch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlStringArg = args[0] as! String
        let prefersDeepLinkArg = args[1] as! Bool
        let optionsArg: SFSafariViewControllerOptions? = nilOrValue(args[2])
        api.launchURL(urlStringArg, prefersDeepLink: prefersDeepLinkArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      launchChannel.setMessageHandler(nil)
    }
    let closeAllIfPossibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.closeAllIfPossible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeAllIfPossibleChannel.setMessageHandler { _, reply in
        api.closeAllIfPossible { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeAllIfPossibleChannel.setMessageHandler(nil)
    }
    let mayLaunchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.mayLaunch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mayLaunchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlStringsArg = args[0] as! [String]
        do {
          let result = try api.mayLaunchURLs(urlStringsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      mayLaunchChannel.setMessageHandler(nil)
    }
    let invalidateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.invalidate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        do {
          try api.invalidateSession(sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      invalidateChannel.setMessageHandler(nil)
    }
  }
}
