// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class SFSafariViewControllerOptions {
  SFSafariViewControllerOptions({
    this.preferredBarTintColor,
    this.preferredControlTintColor,
    this.barCollapsingEnabled,
    this.entersReaderIfAvailable,
    this.dismissButtonStyle,
    this.modalPresentationStyle,
    this.pageSheet,
  });

  int? preferredBarTintColor;

  int? preferredControlTintColor;

  bool? barCollapsingEnabled;

  bool? entersReaderIfAvailable;

  int? dismissButtonStyle;

  int? modalPresentationStyle;

  UISheetPresentationControllerConfiguration? pageSheet;

  List<Object?> _toList() {
    return <Object?>[
      preferredBarTintColor,
      preferredControlTintColor,
      barCollapsingEnabled,
      entersReaderIfAvailable,
      dismissButtonStyle,
      modalPresentationStyle,
      pageSheet,
    ];
  }

  Object encode() {
    return _toList();  }

  static SFSafariViewControllerOptions decode(Object result) {
    result as List<Object?>;
    return SFSafariViewControllerOptions(
      preferredBarTintColor: result[0] as int?,
      preferredControlTintColor: result[1] as int?,
      barCollapsingEnabled: result[2] as bool?,
      entersReaderIfAvailable: result[3] as bool?,
      dismissButtonStyle: result[4] as int?,
      modalPresentationStyle: result[5] as int?,
      pageSheet: result[6] as UISheetPresentationControllerConfiguration?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SFSafariViewControllerOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(preferredBarTintColor, other.preferredBarTintColor) && _deepEquals(preferredControlTintColor, other.preferredControlTintColor) && _deepEquals(barCollapsingEnabled, other.barCollapsingEnabled) && _deepEquals(entersReaderIfAvailable, other.entersReaderIfAvailable) && _deepEquals(dismissButtonStyle, other.dismissButtonStyle) && _deepEquals(modalPresentationStyle, other.modalPresentationStyle) && _deepEquals(pageSheet, other.pageSheet);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SFSafariViewControllerOptions(preferredBarTintColor: $preferredBarTintColor, preferredControlTintColor: $preferredControlTintColor, barCollapsingEnabled: $barCollapsingEnabled, entersReaderIfAvailable: $entersReaderIfAvailable, dismissButtonStyle: $dismissButtonStyle, modalPresentationStyle: $modalPresentationStyle, pageSheet: $pageSheet)';
  }
}

class UISheetPresentationControllerConfiguration {
  UISheetPresentationControllerConfiguration({
    required this.detents,
    this.largestUndimmedDetentIdentifier,
    this.prefersScrollingExpandsWhenScrolledToEdge,
    this.prefersGrabberVisible,
    this.prefersEdgeAttachedInCompactHeight,
    this.preferredCornerRadius,
  });

  List<String> detents;

  String? largestUndimmedDetentIdentifier;

  bool? prefersScrollingExpandsWhenScrolledToEdge;

  bool? prefersGrabberVisible;

  bool? prefersEdgeAttachedInCompactHeight;

  double? preferredCornerRadius;

  List<Object?> _toList() {
    return <Object?>[
      detents,
      largestUndimmedDetentIdentifier,
      prefersScrollingExpandsWhenScrolledToEdge,
      prefersGrabberVisible,
      prefersEdgeAttachedInCompactHeight,
      preferredCornerRadius,
    ];
  }

  Object encode() {
    return _toList();  }

  static UISheetPresentationControllerConfiguration decode(Object result) {
    result as List<Object?>;
    return UISheetPresentationControllerConfiguration(
      detents: (result[0]! as List<Object?>).cast<String>(),
      largestUndimmedDetentIdentifier: result[1] as String?,
      prefersScrollingExpandsWhenScrolledToEdge: result[2] as bool?,
      prefersGrabberVisible: result[3] as bool?,
      prefersEdgeAttachedInCompactHeight: result[4] as bool?,
      preferredCornerRadius: result[5] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UISheetPresentationControllerConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(detents, other.detents) && _deepEquals(largestUndimmedDetentIdentifier, other.largestUndimmedDetentIdentifier) && _deepEquals(prefersScrollingExpandsWhenScrolledToEdge, other.prefersScrollingExpandsWhenScrolledToEdge) && _deepEquals(prefersGrabberVisible, other.prefersGrabberVisible) && _deepEquals(prefersEdgeAttachedInCompactHeight, other.prefersEdgeAttachedInCompactHeight) && _deepEquals(preferredCornerRadius, other.preferredCornerRadius);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UISheetPresentationControllerConfiguration(detents: $detents, largestUndimmedDetentIdentifier: $largestUndimmedDetentIdentifier, prefersScrollingExpandsWhenScrolledToEdge: $prefersScrollingExpandsWhenScrolledToEdge, prefersGrabberVisible: $prefersGrabberVisible, prefersEdgeAttachedInCompactHeight: $prefersEdgeAttachedInCompactHeight, preferredCornerRadius: $preferredCornerRadius)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SFSafariViewControllerOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is UISheetPresentationControllerConfiguration) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SFSafariViewControllerOptions.decode(readValue(buffer)!);
      case 130:
        return UISheetPresentationControllerConfiguration.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CustomTabsApi {
  /// Constructor for [CustomTabsApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CustomTabsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> launch(String urlString, {required bool prefersDeepLink, SFSafariViewControllerOptions? options, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.launch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[urlString, prefersDeepLink, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> closeAllIfPossible() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.closeAllIfPossible$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String?> mayLaunch(List<String> urlStrings) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.mayLaunch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[urlStrings]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<void> invalidate(String sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_custom_tabs_ios.CustomTabsApi.invalidate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
